### ISSUE TITLE
Error handling iOS SDK

### ISSUE THREAD

**Issue by terencebls** [openTdataCH/ojp-ios#18]

**Comment by r3to** [comment]
- OJPError type defined by VDV https://vdvde.github.io/OJP/develop/index.html#OJPError
- Examples: https://github.com/VDVde/OJP/tree/develop/examples/functions/error
- Discussion about current state and observed issues: 
  - https://github.com/openTdataCH/ojp-sdk/issues/3 
  - https://github.com/openTdataCH/ojp-sdk/blob/main/documentation/api_errors.md
